/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DanePodatkoweRouteImport } from './routes/dane-podatkowe'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExchangesRouteImport } from './routes/exchanges'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as MojeDaneRouteImport } from './routes/moje-dane'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as ReportInfringementRouteImport } from './routes/report-infringement'
import { Route as ResetHaslaRouteImport } from './routes/reset-hasla'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as SporyTransactionIdRouteImport } from './routes/spory.$transactionId'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DanePodatkoweRoute = DanePodatkoweRouteImport.update({
  id: '/dane-podatkowe',
  path: '/dane-podatkowe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesRoute = ExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const MojeDaneRoute = MojeDaneRouteImport.update({
  id: '/moje-dane',
  path: '/moje-dane',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportInfringementRoute = ReportInfringementRouteImport.update({
  id: '/report-infringement',
  path: '/report-infringement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetHaslaRoute = ResetHaslaRouteImport.update({
  id: '/reset-hasla',
  path: '/reset-hasla',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SporyTransactionIdRoute = SporyTransactionIdRouteImport.update({
  id: '/spory/$transactionId',
  path: '/spory/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dane-podatkowe': typeof DanePodatkoweRoute
  '/dashboard': typeof DashboardRoute
  '/exchanges': typeof ExchangesRoute
  '/help': typeof HelpRoute
  '/likes': typeof LikesRoute
  '/moje-dane': typeof MojeDaneRoute
  '/notifications': typeof NotificationsRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/report-infringement': typeof ReportInfringementRoute
  '/reset-hasla': typeof ResetHaslaRoute
  '/sell': typeof SellRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/product/$id': typeof ProductIdRoute
  '/spory/$transactionId': typeof SporyTransactionIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dane-podatkowe': typeof DanePodatkoweRoute
  '/dashboard': typeof DashboardRoute
  '/exchanges': typeof ExchangesRoute
  '/help': typeof HelpRoute
  '/likes': typeof LikesRoute
  '/moje-dane': typeof MojeDaneRoute
  '/notifications': typeof NotificationsRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/report-infringement': typeof ReportInfringementRoute
  '/reset-hasla': typeof ResetHaslaRoute
  '/sell': typeof SellRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/product/$id': typeof ProductIdRoute
  '/spory/$transactionId': typeof SporyTransactionIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages': typeof MessagesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dane-podatkowe': typeof DanePodatkoweRoute
  '/dashboard': typeof DashboardRoute
  '/exchanges': typeof ExchangesRoute
  '/help': typeof HelpRoute
  '/likes': typeof LikesRoute
  '/moje-dane': typeof MojeDaneRoute
  '/notifications': typeof NotificationsRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/report-infringement': typeof ReportInfringementRoute
  '/reset-hasla': typeof ResetHaslaRoute
  '/sell': typeof SellRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/product/$id': typeof ProductIdRoute
  '/spory/$transactionId': typeof SporyTransactionIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dane-podatkowe'
    | '/dashboard'
    | '/exchanges'
    | '/help'
    | '/likes'
    | '/moje-dane'
    | '/notifications'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/report-infringement'
    | '/reset-hasla'
    | '/sell'
    | '/messages/$userId'
    | '/product/$id'
    | '/spory/$transactionId'
    | '/u/$username'
    | '/messages/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dane-podatkowe'
    | '/dashboard'
    | '/exchanges'
    | '/help'
    | '/likes'
    | '/moje-dane'
    | '/notifications'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/report-infringement'
    | '/reset-hasla'
    | '/sell'
    | '/messages/$userId'
    | '/product/$id'
    | '/spory/$transactionId'
    | '/u/$username'
    | '/messages'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dane-podatkowe'
    | '/dashboard'
    | '/exchanges'
    | '/help'
    | '/likes'
    | '/moje-dane'
    | '/notifications'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/report-infringement'
    | '/reset-hasla'
    | '/sell'
    | '/messages/$userId'
    | '/product/$id'
    | '/spory/$transactionId'
    | '/u/$username'
    | '/messages/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DanePodatkoweRoute: typeof DanePodatkoweRoute
  DashboardRoute: typeof DashboardRoute
  ExchangesRoute: typeof ExchangesRoute
  HelpRoute: typeof HelpRoute
  LikesRoute: typeof LikesRoute
  MojeDaneRoute: typeof MojeDaneRoute
  NotificationsRoute: typeof NotificationsRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RegulaminRoute: typeof RegulaminRoute
  ReportInfringementRoute: typeof ReportInfringementRoute
  ResetHaslaRoute: typeof ResetHaslaRoute
  SellRoute: typeof SellRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  ProductIdRoute: typeof ProductIdRoute
  SporyTransactionIdRoute: typeof SporyTransactionIdRoute
  UUsernameRoute: typeof UUsernameRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dane-podatkowe': {
      id: '/dane-podatkowe'
      path: '/dane-podatkowe'
      fullPath: '/dane-podatkowe'
      preLoaderRoute: typeof DanePodatkoweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges': {
      id: '/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof ExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moje-dane': {
      id: '/moje-dane'
      path: '/moje-dane'
      fullPath: '/moje-dane'
      preLoaderRoute: typeof MojeDaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-infringement': {
      id: '/report-infringement'
      path: '/report-infringement'
      fullPath: '/report-infringement'
      preLoaderRoute: typeof ReportInfringementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-hasla': {
      id: '/reset-hasla'
      path: '/reset-hasla'
      fullPath: '/reset-hasla'
      preLoaderRoute: typeof ResetHaslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spory/$transactionId': {
      id: '/spory/$transactionId'
      path: '/spory/$transactionId'
      fullPath: '/spory/$transactionId'
      preLoaderRoute: typeof SporyTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DanePodatkoweRoute: DanePodatkoweRoute,
  DashboardRoute: DashboardRoute,
  ExchangesRoute: ExchangesRoute,
  HelpRoute: HelpRoute,
  LikesRoute: LikesRoute,
  MojeDaneRoute: MojeDaneRoute,
  NotificationsRoute: NotificationsRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RegulaminRoute: RegulaminRoute,
  ReportInfringementRoute: ReportInfringementRoute,
  ResetHaslaRoute: ResetHaslaRoute,
  SellRoute: SellRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  ProductIdRoute: ProductIdRoute,
  SporyTransactionIdRoute: SporyTransactionIdRoute,
  UUsernameRoute: UUsernameRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
